# ===================================================================
# Common Application Configuration
# ===================================================================
spring.application.name=student-api

# Default profile if none is explicitly specified
spring.profiles.default=local
spring.profiles.active=local

# Server Port
server.port=8080

# JPA common settings
spring.jpa.open-in-view=false
